#!/usr/bin/env python3
"""Read-only quality triage for papers.yaml.

Flags low-quality / off-topic / unverifiable entries so a human (or a later
cleanup step) can review them. Extracts nothing, deletes nothing: output is a
reviewable markdown report (default) or JSON.

Signals (built to be low-false-positive, flag-only):
  - vanity-platform : non-peer-reviewed preprint platforms (Research Square,
    preprints.org, techrxiv, hal.science, zenodo-oi, rgdoi)
  - no-abstract     : no abstract AND not from arXiv/DBLP (bulk-OpenAlex junk)
  - off-topic       : title/abstract clearly outside the software-development
                      domain (irrigation, climate models, pharma, ...)
  - junk-venue      : suspicious non-peer-reviewed venue names

Each flag carries a weight; entries are ranked by total suspicion score.

Usage:
    python3 tools/triage_corpus.py                 # markdown to stdout + report
    python3 tools/triage_corpus.py --limit 200     # top 200 entries in detail
    python3 tools/triage_corpus.py --json          # machine-readable
    python3 tools/triage_corpus.py --out /dev/null # count summary only
"""

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
import research_config as rc

REPO = Path(__file__).resolve().parent.parent

# --- signals ----------------------------------------------------------------

VANITY_URL = re.compile(
    r"(researchsquare\.com|10\.21203|rgdoi\.net|preprints\.org|techrxiv\.org|"
    r"hal\.science|zenodo\.org/doi)",
    re.IGNORECASE,
)

FOREIGN_TOPIC = re.compile(
    r"\b(irrigation|furrow|crop yield|lactat|human milk|milk bank|breastfeed|"
    r"chemotherap|pharmaceutical|veterinary|livestock|genomic|protein engineer|"
    r"bioproduct|marine science|aquatic|climate model|spacecraft "
    r"attitude|manure|microbiome|nutrigenomic|soil sensor|satellite imag|"
    r"pesticide|fertilizer|greenhouse gas|anaerobic digestion)\b",
    re.IGNORECASE,
)

JUNK_VENUE = re.compile(
    r"(Global Research in Multidisciplinary Studies|ijcope|comcomponent|"
    r"Direct Research Journal|International Journal of [A-Za-z &]+Research in "
    r"Engineering and Management|Asian Journal of (?:Research|Pure|Advances))",
    re.IGNORECASE,
)

VETTED_HOSTS = ("arxiv.org", "dblp.org")

FLAG_NAMES = {
    "vanity-platform": "non-peer-reviewed platform",
    "no-abstract": "no abstract (unvetted source)",
    "off-topic": "outside software-development domain",
    "junk-venue": "suspicious venue",
}


def flags_for(paper):
    """Return list of (flag_id, weight, detail) for a paper; [] if clean."""
    flags = []
    url = paper.get("url", "") or ""
    title = paper.get("title", "") or ""
    abst = paper.get("abstract") or ""
    venue = paper.get("venue", "") or ""
    if isinstance(venue, list):
        venue = ", ".join(str(v) for v in venue)

    if VANITY_URL.search(url):
        flags.append(("vanity-platform", 4,
                      f"URL {url[:70]} is a non-peer-reviewed platform"))

    if not abst and not any(h in url for h in VETTED_HOSTS):
        flags.append(("no-abstract", 2,
                      "no abstract and not arXiv/DBLP (bulk ingest candidate)"))

    m = FOREIGN_TOPIC.search(f"{title} {abst}")
    if m:
        flags.append(("off-topic", 3,
                      f"'{m.group(0)}' in title/abstract (foreign domain)"))

    if venue and JUNK_VENUE.search(venue):
        flags.append(("junk-venue", 3, f"venue '{venue[:60]}' looks non-peer-reviewed"))

    return flags


def score_flags(flags):
    return sum(w for _, w, _ in flags)


def scan(papers):
    """Return list of (score, flags, paper) for flagged papers, sorted desc."""
    scored = []
    for p in papers:
        fl = flags_for(p)
        if fl:
            scored.append((score_flags(fl), fl, p))
    scored.sort(key=lambda x: -x[0])
    return scored


def render_markdown(scored, total):
    lines = []
    lines.append("# Corpus Triage Report")
    lines.append("")
    lines.append(f"> Generated by `tools/triage_corpus.py` — do not edit by hand.")
    lines.append(f"> {total} papers scanned; {len(scored)} flagged. Read-only: nothing was removed.")
    lines.append("")
    lines.append("## By flag")
    lines.append("")
    from collections import Counter
    counts = Counter(fid for _, fl, _ in scored for fid, _, _ in fl)
    for fid in FLAG_NAMES:
        lines.append(f"- **{fid}** ({FLAG_NAMES[fid]}): {counts.get(fid, 0)}")
    lines.append("")
    lines.append(f"## Flagged entries (top {min(50, len(scored))})")
    lines.append("")
    for score, fl, p in scored[:50]:
        d = (p.get("date") or "")[:4]
        title = p.get("title", "")
        url = p.get("url", "")
        why = "; ".join(f"{fid}:{w}" for fid, w, _ in fl)
        lines.append(f"- [{score}] ({d}) **{title}**"
                     f" [[paper]({url})] — {why}")
    lines.append("")
    lines.append(f"Full machine-readable list: `tools/triage_corpus.py --json`.")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, default=50, help="detail rows (default 50)")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of markdown")
    ap.add_argument("--out", default=str(REPO / "docs" / "research" / "corpus_triage.md"),
                    help="write report here (default docs/research/corpus_triage.md)")
    args = ap.parse_args()

    papers = rc.load_papers()
    scored = scan(papers)
    print(f"Scanned {len(papers)} papers; flagged {len(scored)} "
          f"({len(scored) / len(papers) * 100:.1f}%).")

    if args.json:
        out = {
            "total_papers": len(papers),
            "flagged": len(scored),
            "entries": [
                {"score": s, "flags": [f for f, _, _ in fl],
                 "title": p.get("title"), "url": p.get("url"), "date": p.get("date")}
                for s, fl, p in scored
            ],
        }
        print(json.dumps(out, ensure_ascii=False, indent=2))
        return

    text = render_markdown(scored, len(papers))
    if args.out and args.out != "/dev/null":
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"Wrote {args.out}")
    else:
        print(text)


if __name__ == "__main__":
    main()
